INSERT INTO words (word) VALUES ('Bad');
INSERT INTO words (word) VALUES ('Ill');
INSERT INTO words (word) VALUES ('Odd');
INSERT INTO words (word) VALUES ('Shy');
INSERT INTO words (word) VALUES ('Blue');
INSERT INTO words (word) VALUES ('Busy');
INSERT INTO words (word) VALUES ('Calm');
INSERT INTO words (word) VALUES ('Cute');
INSERT INTO words (word) VALUES ('Dark');
INSERT INTO words (word) VALUES ('Dead');
INSERT INTO words (word) VALUES ('Drab');
INSERT INTO words (word) VALUES ('Dull');
INSERT INTO words (word) VALUES ('Easy');
INSERT INTO words (word) VALUES ('Evil');
INSERT INTO words (word) VALUES ('Fair');
INSERT INTO words (word) VALUES ('Fine');
INSERT INTO words (word) VALUES ('Good');
INSERT INTO words (word) VALUES ('Hurt');
INSERT INTO words (word) VALUES ('Kind');
INSERT INTO words (word) VALUES ('Lazy');
INSERT INTO words (word) VALUES ('Long');
INSERT INTO words (word) VALUES ('Nice');
INSERT INTO words (word) VALUES ('Open');
INSERT INTO words (word) VALUES ('Poor');
INSERT INTO words (word) VALUES ('Real');
INSERT INTO words (word) VALUES ('Rich');
INSERT INTO words (word) VALUES ('Sore');
INSERT INTO words (word) VALUES ('Tame');
INSERT INTO words (word) VALUES ('Ugly');
INSERT INTO words (word) VALUES ('Vast');
INSERT INTO words (word) VALUES ('Wild');
INSERT INTO words (word) VALUES ('Zany');
INSERT INTO words (word) VALUES ('Alert');
INSERT INTO words (word) VALUES ('Alive');
INSERT INTO words (word) VALUES ('Angry');
INSERT INTO words (word) VALUES ('Awful');
INSERT INTO words (word) VALUES ('Black');
INSERT INTO words (word) VALUES ('Bored');
INSERT INTO words (word) VALUES ('Brave');
INSERT INTO words (word) VALUES ('Clean');
INSERT INTO words (word) VALUES ('Clear');
INSERT INTO words (word) VALUES ('Crazy');
INSERT INTO words (word) VALUES ('Cruel');
INSERT INTO words (word) VALUES ('Dizzy');
INSERT INTO words (word) VALUES ('Eager');
INSERT INTO words (word) VALUES ('Fancy');
INSERT INTO words (word) VALUES ('Frail');
INSERT INTO words (word) VALUES ('Funny');
INSERT INTO words (word) VALUES ('Happy');
INSERT INTO words (word) VALUES ('Itchy');
INSERT INTO words (word) VALUES ('Jolly');
INSERT INTO words (word) VALUES ('Light');
INSERT INTO words (word) VALUES ('Lucky');
INSERT INTO words (word) VALUES ('Misty');
INSERT INTO words (word) VALUES ('Muddy');
INSERT INTO words (word) VALUES ('Mushy');
INSERT INTO words (word) VALUES ('Nasty');
INSERT INTO words (word) VALUES ('Nutty');
INSERT INTO words (word) VALUES ('Plain');
INSERT INTO words (word) VALUES ('Proud');
INSERT INTO words (word) VALUES ('Scary');
INSERT INTO words (word) VALUES ('Shiny');
INSERT INTO words (word) VALUES ('Silly');
INSERT INTO words (word) VALUES ('Super');
INSERT INTO words (word) VALUES ('Tense');
INSERT INTO words (word) VALUES ('Tasty');
INSERT INTO words (word) VALUES ('Tired');
INSERT INTO words (word) VALUES ('Tough');
INSERT INTO words (word) VALUES ('Upset');
INSERT INTO words (word) VALUES ('Weary');
INSERT INTO words (word) VALUES ('Witty');
INSERT INTO words (word) VALUES ('Wrong');
INSERT INTO words (word) VALUES ('Amused');
INSERT INTO words (word) VALUES ('Better');
INSERT INTO words (word) VALUES ('Bloody');
INSERT INTO words (word) VALUES ('Brainy');
INSERT INTO words (word) VALUES ('Bright');
INSERT INTO words (word) VALUES ('Clever');
INSERT INTO words (word) VALUES ('Cloudy');
INSERT INTO words (word) VALUES ('Clumsy');
INSERT INTO words (word) VALUES ('Creepy');
INSERT INTO words (word) VALUES ('Elated');
INSERT INTO words (word) VALUES ('Famous');
INSERT INTO words (word) VALUES ('Fierce');
INSERT INTO words (word) VALUES ('Filthy');
INSERT INTO words (word) VALUES ('Gentle');
INSERT INTO words (word) VALUES ('Gifted');
INSERT INTO words (word) VALUES ('Grumpy');
INSERT INTO words (word) VALUES ('Homely');
INSERT INTO words (word) VALUES ('Hungry');
INSERT INTO words (word) VALUES ('Joyous');
INSERT INTO words (word) VALUES ('Lively');
INSERT INTO words (word) VALUES ('Lonely');
INSERT INTO words (word) VALUES ('Lovely');
INSERT INTO words (word) VALUES ('Modern');
INSERT INTO words (word) VALUES ('Poised');
INSERT INTO words (word) VALUES ('Putrid');
INSERT INTO words (word) VALUES ('Quaint');
INSERT INTO words (word) VALUES ('Sleepy');
INSERT INTO words (word) VALUES ('Smoggy');
INSERT INTO words (word) VALUES ('Stormy');
INSERT INTO words (word) VALUES ('Stupid');
INSERT INTO words (word) VALUES ('Tender');
INSERT INTO words (word) VALUES ('Wicked');
INSERT INTO words (word) VALUES ('Annoyed');
INSERT INTO words (word) VALUES ('Anxious');
INSERT INTO words (word) VALUES ('Ashamed');
INSERT INTO words (word) VALUES ('Average');
INSERT INTO words (word) VALUES ('Careful');
INSERT INTO words (word) VALUES ('Crowded');
INSERT INTO words (word) VALUES ('Curious');
INSERT INTO words (word) VALUES ('Defiant');
INSERT INTO words (word) VALUES ('Elegant');
INSERT INTO words (word) VALUES ('Envious');
INSERT INTO words (word) VALUES ('Excited');
INSERT INTO words (word) VALUES ('Foolish');
INSERT INTO words (word) VALUES ('Fragile');
INSERT INTO words (word) VALUES ('Frantic');
INSERT INTO words (word) VALUES ('Healthy');
INSERT INTO words (word) VALUES ('Helpful');
INSERT INTO words (word) VALUES ('Jealous');
INSERT INTO words (word) VALUES ('Jittery');
INSERT INTO words (word) VALUES ('Naughty');
INSERT INTO words (word) VALUES ('Nervous');
INSERT INTO words (word) VALUES ('Panicky');
INSERT INTO words (word) VALUES ('Perfect');
INSERT INTO words (word) VALUES ('Prickly');
INSERT INTO words (word) VALUES ('Puzzled');
INSERT INTO words (word) VALUES ('Selfish');
INSERT INTO words (word) VALUES ('Smiling');
INSERT INTO words (word) VALUES ('Strange');
INSERT INTO words (word) VALUES ('Ugliest');
INSERT INTO words (word) VALUES ('Unusual');
INSERT INTO words (word) VALUES ('Uptight');
INSERT INTO words (word) VALUES ('Worried');
INSERT INTO words (word) VALUES ('Zealous');
INSERT INTO words (word) VALUES ('Adorable');
INSERT INTO words (word) VALUES ('Annoying');
INSERT INTO words (word) VALUES ('Arrogant');
INSERT INTO words (word) VALUES ('Blushing');
INSERT INTO words (word) VALUES ('Cautious');
INSERT INTO words (word) VALUES ('Charming');
INSERT INTO words (word) VALUES ('Cheerful');
INSERT INTO words (word) VALUES ('Colorful');
INSERT INTO words (word) VALUES ('Confused');
INSERT INTO words (word) VALUES ('Defeated');
INSERT INTO words (word) VALUES ('Distinct');
INSERT INTO words (word) VALUES ('Doubtful');
INSERT INTO words (word) VALUES ('Faithful');
INSERT INTO words (word) VALUES ('Friendly');
INSERT INTO words (word) VALUES ('Gleaming');
INSERT INTO words (word) VALUES ('Glorious');
INSERT INTO words (word) VALUES ('Gorgeous');
INSERT INTO words (word) VALUES ('Graceful');
INSERT INTO words (word) VALUES ('Grieving');
INSERT INTO words (word) VALUES ('Handsome');
INSERT INTO words (word) VALUES ('Helpless');
INSERT INTO words (word) VALUES ('Homeless');
INSERT INTO words (word) VALUES ('Horrible');
INSERT INTO words (word) VALUES ('Innocent');
INSERT INTO words (word) VALUES ('Obedient');
INSERT INTO words (word) VALUES ('Pleasant');
INSERT INTO words (word) VALUES ('Powerful');
INSERT INTO words (word) VALUES ('Precious');
INSERT INTO words (word) VALUES ('Relieved');
INSERT INTO words (word) VALUES ('Splendid');
INSERT INTO words (word) VALUES ('Spotless');
INSERT INTO words (word) VALUES ('Talented');
INSERT INTO words (word) VALUES ('Terrible');
INSERT INTO words (word) VALUES ('Thankful');
INSERT INTO words (word) VALUES ('Troubled');
INSERT INTO words (word) VALUES ('Agreeable');
INSERT INTO words (word) VALUES ('Beautiful');
INSERT INTO words (word) VALUES ('Blue-eyed');
INSERT INTO words (word) VALUES ('Breakable');
INSERT INTO words (word) VALUES ('Combative');
INSERT INTO words (word) VALUES ('Concerned');
INSERT INTO words (word) VALUES ('Condemned');
INSERT INTO words (word) VALUES ('Dangerous');
INSERT INTO words (word) VALUES ('Depressed');
INSERT INTO words (word) VALUES ('Different');
INSERT INTO words (word) VALUES ('Difficult');
INSERT INTO words (word) VALUES ('Disgusted');
INSERT INTO words (word) VALUES ('Disturbed');
INSERT INTO words (word) VALUES ('Energetic');
INSERT INTO words (word) VALUES ('Expensive');
INSERT INTO words (word) VALUES ('Exuberant');
INSERT INTO words (word) VALUES ('Fantastic');
INSERT INTO words (word) VALUES ('Glamorous');
INSERT INTO words (word) VALUES ('Grotesque');
INSERT INTO words (word) VALUES ('Hilarious');
INSERT INTO words (word) VALUES ('Important');
INSERT INTO words (word) VALUES ('Obnoxious');
INSERT INTO words (word) VALUES ('Repulsive');
INSERT INTO words (word) VALUES ('Sparkling');
INSERT INTO words (word) VALUES ('Unsightly');
INSERT INTO words (word) VALUES ('Vivacious');
INSERT INTO words (word) VALUES ('Wandering');
INSERT INTO words (word) VALUES ('Wide-eyed');
INSERT INTO words (word) VALUES ('Worrisome');
INSERT INTO words (word) VALUES ('Aggressive');
INSERT INTO words (word) VALUES ('Attractive');
INSERT INTO words (word) VALUES ('Bewildered');
INSERT INTO words (word) VALUES ('Courageous');
INSERT INTO words (word) VALUES ('Delightful');
INSERT INTO words (word) VALUES ('Determined');
INSERT INTO words (word) VALUES ('Enchanting');
INSERT INTO words (word) VALUES ('Frightened');
INSERT INTO words (word) VALUES ('Impossible');
INSERT INTO words (word) VALUES ('Motionless');
INSERT INTO words (word) VALUES ('Mysterious');
INSERT INTO words (word) VALUES ('Outrageous');
INSERT INTO words (word) VALUES ('Successful');
INSERT INTO words (word) VALUES ('Thoughtful');
INSERT INTO words (word) VALUES ('Victorious');
INSERT INTO words (word) VALUES ('Adventurous');
INSERT INTO words (word) VALUES ('Comfortable');
INSERT INTO words (word) VALUES ('Cooperative');
INSERT INTO words (word) VALUES ('Embarrassed');
INSERT INTO words (word) VALUES ('Encouraging');
INSERT INTO words (word) VALUES ('Inexpensive');
INSERT INTO words (word) VALUES ('Inquisitive');
INSERT INTO words (word) VALUES ('Magnificent');
INSERT INTO words (word) VALUES ('Outstanding');
INSERT INTO words (word) VALUES ('Thoughtless');
INSERT INTO words (word) VALUES ('Enthusiastic');
INSERT INTO words (word) VALUES ('Uninterested');
INSERT INTO words (word) VALUES ('Old-fashioned');



INSERT INTO cheesy_sentence (sentence) VALUES ('"Your time is limited, so dont waste it living someone elses life. Dont be trapped by dogma – which is living with the results of other peoples thinking." -Steve Jobs');
INSERT INTO cheesy_sentence (sentence) VALUES ('"You will face many defeats in life, but never let yourself be defeated." -Maya Angelou');
INSERT INTO cheesy_sentence (sentence) VALUES ('"You have brains in your head. You have feet in your shoes. You can steer yourself any direction you choose." -Dr. Seuss');
INSERT INTO cheesy_sentence (sentence) VALUES ('"Whoever is happy will make others happy too." -Anne Frank');
INSERT INTO cheesy_sentence (sentence) VALUES ('"When you reach the end of your rope, tie a knot in it and hang on." -Franklin D. Roosevelt');
INSERT INTO cheesy_sentence (sentence) VALUES ('"The way to get started is to quit talking and begin doing." -Walt Disney');
INSERT INTO cheesy_sentence (sentence) VALUES ('"The secret of success is to do the common thing uncommonly well." -John D. Rockefeller Jr.');
INSERT INTO cheesy_sentence (sentence) VALUES ('"The real test is not whether you avoid this failure, because you wont. Its whether you let it harden or shame you into inaction, or whether you learn from it; whether you choose to persevere." -Barack Obama');
INSERT INTO cheesy_sentence (sentence) VALUES ('"The greatest glory in living lies not in never falling, but in rising every time we fall." -Nelson Mandela');
INSERT INTO cheesy_sentence (sentence) VALUES ('"The future belongs to those who believe in the beauty of their dreams." -Eleanor Roosevelt');
INSERT INTO cheesy_sentence (sentence) VALUES ('"The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart." -Helen Keller');
INSERT INTO cheesy_sentence (sentence) VALUES ('"Tell me and I forget. Teach me and I remember. Involve me and I learn." -Benjamin Franklin');
INSERT INTO cheesy_sentence (sentence) VALUES ('"Success usually comes to those who are too busy to be looking for it." -Henry David Thoreau');
INSERT INTO cheesy_sentence (sentence) VALUES ('"Success is not final; failure is not fatal: It is the courage to continue that counts." -Winston S. Churchill');
INSERT INTO cheesy_sentence (sentence) VALUES ('"Spread love everywhere you go. Let no one ever come to you without leaving happier." -Mother Teresa');
INSERT INTO cheesy_sentence (sentence) VALUES ('"Never let the fear of striking out keep you from playing the game." -Babe Ruth');
INSERT INTO cheesy_sentence (sentence) VALUES ('"Many of lifes failures are people who did not realize how close they were to success when they gave up." -Thomas A. Edison');
INSERT INTO cheesy_sentence (sentence) VALUES ('"Life is what happens when youre busy making other plans." -John Lennon');
INSERT INTO cheesy_sentence (sentence) VALUES ('"Life is either a daring adventure or nothing at all." -Helen Keller');
INSERT INTO cheesy_sentence (sentence) VALUES ('"It is during our darkest moments that we must focus to see the light." -Aristotle');
INSERT INTO cheesy_sentence (sentence) VALUES ('"In the end, its not the years in your life that count. Its the life in your years." -Abraham Lincoln');
INSERT INTO cheesy_sentence (sentence) VALUES ('"If you set your goals ridiculously high and its a failure, you will fail above everyone elses success." -James Cameron');
INSERT INTO cheesy_sentence (sentence) VALUES ('"If you really look closely, most overnight successes took a long time." -Steve Jobs');
INSERT INTO cheesy_sentence (sentence) VALUES ('"If you look at what you have in life, youll always have more. If you look at what you dont have in life, youll never have enough." -Oprah Winfrey');
INSERT INTO cheesy_sentence (sentence) VALUES ('"If life were predictable it would cease to be life, and be without flavor." -Eleanor Roosevelt');
INSERT INTO cheesy_sentence (sentence) VALUES ('"I find that the harder I work, the more luck I seem to have." -Thomas Jefferson');
INSERT INTO cheesy_sentence (sentence) VALUES ('"Dont judge each day by the harvest you reap but by the seeds that you plant." -Robert Louis Stevenson');
INSERT INTO cheesy_sentence (sentence) VALUES ('"Do not go where the path may lead, go instead where there is no path and leave a trail." -Ralph Waldo Emerson');
INSERT INTO cheesy_sentence (sentence) VALUES ('"Always remember that you are absolutely unique. Just like everyone else." -Margaret Mead');